"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$cpp\
$cmake\
$cobol\
$conda\
$container\
$crystal\
$dart\
$deno\
$elixir\
$elm\
$fennel\
$fortran\
$golang\
$gradle\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$maven\
$nodejs\
$bun\
$nim\
$rust\
$scala\
$openstack\
$perl\
$php\
$python\
$pulumi\
$rlang\
$ruby\
$scala\
$swift\
$aws\
$azure\
$gcloud\
$terraform\
$xmake\
$zig\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false# Disabled by default

[directory]
read_only = " 󰌾"
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
#"Dev" = " "
"Public" = " "
"Desktop" = "󰛳 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[maven]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version )(($virtualenv) ) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'

[aws]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[azure]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[buf]
symbol = " "

[cmake]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cobol]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[container]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[crystal]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[deno]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[direnv]
symbol = " "

[dotnet]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[erlang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[fennel]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[fortran]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gleam]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_commit]
tag_symbol = '  '

[guix_shell]
symbol = " "

[haxe]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[helm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[kotlin]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "󱃾 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[mojo]
symbol = "󰈸 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nats]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[netns]
symbol = "󰛳 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[odin]
symbol = "󰟢 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[opa]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[openstack]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[pulumi]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[purescript]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[raku]
symbol = "󱖊 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[red]
symbol = "󱍼 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rlang]
symbol = "󰟔 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[shlvl]
symbol = "󰹍 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[singularity]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[solidity]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[spack]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[status]
symbol = " "

[sudo]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[terraform]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[vlang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[typst]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[vagrant]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[xmake]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'
